We dont have labels - lets say we dont know if a text is positive, negative, neutral. 
WHAT do we do? 
We do - VADER 

calence aware dictionary for sentiment reasoning. It is sensitive to polarity (positive / negative) and intensity (strength) of emotion 

Its analysis relised on a dictionary which maos lexical features to emotion intensities called sentiment scores. 
The sentiment score of a text can be ontained by summing up the intensity of each word in the text.

We take all the words in a doc - we calculate positive or negative emotions and sum them all up to see the final result of a document

VADER also takes in consideration relation of a word wth its surroundng words and punctuations.

In [1]:
import nltk

In [2]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...

True

In [3]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [4]:
sid = SentimentIntensityAnalyzer()

In [5]:
a = "This is a good movie"

In [6]:
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

This sid have 4 options - negative, positive, neutral, and compound - COMPUND IS THE OVERALL IDEA - IF SOMETHING IS POSITIVE OR NEGATIVE 
But it gives scores for all 4 options.

In [7]:
a = "This was the best, most awesome movie EVER Made!!"

In [8]:
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.433, 'pos': 0.567, 'compound': 0.88}

In [11]:
a = "This was the worst movie that has EVER DISGRACED the screen"

In [12]:
sid.polarity_scores(a)

{'neg': 0.465, 'neu': 0.535, 'pos': 0.0, 'compound': -0.8331}

In [13]:
a = "This was the WORST movie that has ever dusgraced the screen"

In [14]:
sid.polarity_scores(a)

{'neg': 0.326, 'neu': 0.674, 'pos': 0.0, 'compound': -0.7034}

Eve the capitals work.

In [15]:
import pandas as pd

In [39]:
df = pd.read_csv("L:\\Workspace\\Resources\\UPDATED_NLP_COURSE\\TextFiles\\amazonreviews.tsv", sep= '\t')

In [18]:
df.head()

  label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [34]:
df.isnull().sum()

label     0
review    0
dtype: int64

In [20]:
df[(df['label']=='') | (df['label'].str.strip()=='')]

Empty DataFrame
Columns: [label, review]
Index: []

In [21]:
df[(df['review']=='') | (df['review'].str.strip()=='')]

Empty DataFrame
Columns: [label, review]
Index: []

In [22]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [40]:
df.dropna(inplace = True)

In [24]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [25]:
sid.polarity_scores(df.iloc[0]['review'])

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [27]:
df.iloc[0]['review']

'Stuning even for the non-gamer: This sound track was beautiful! It paints the senery in your mind so well I would recomend it even to people who hate vid. game music! I have played the game Chrono Cross but out of all of the games I have ever played it has the best music! It backs away from crude keyboarding and takes a fresher step with grate guitars and soulful orchestras. It would impress anyone who cares to listen! ^_^'

In [28]:
df.iloc[0]['label']

'pos'

In [41]:
df['scores'] = df['review'].apply(lambda review : sid.polarity_scores(review))

In [42]:
df.head()

,label,review,scores
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co..."
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co..."
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com..."
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com..."
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp..."

In [43]:
df['compound'] = df['scores'].apply(lambda d: d['compound'])

In [44]:
df.head()

,label,review,scores,compound
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...",0.9454
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...",0.8957
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...",0.9858
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...",0.9814
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...",0.9781

In [46]:
df['comp_score'] = df['compound'].apply(lambda score : 'pos' if score >= 0 else 'neg')

In [48]:
df.head()

,label,review,scores,compound,comp_score
0,pos,Stuning even for the non-gamer: This sound tra...,"{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...",0.9454,pos
1,pos,The best soundtrack ever to anything.: I'm rea...,"{'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...",0.8957,pos
2,pos,Amazing!: This soundtrack is my favorite music...,"{'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...",0.9858,pos
3,pos,Excellent Soundtrack: I truly like this soundt...,"{'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...",0.9814,pos
4,pos,"Remember, Pull Your Jaw Off The Floor After He...","{'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...",0.9781,pos

In [52]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [50]:
accuracy_score(df['label'] , df['comp_score'])

0.7098

So - here. I checked actual label column - with my created comp_score - and why comp_score? Because we created it using sid.polarities - a new model 
So we test it - and see how it is actually working. 
This is called using ML and AI for our work - instead of creating a new model and trauining and testing it.

In [51]:
print(classification_report(df['label'], df['comp_score']))

              precision    recall  f1-score   support

         neg       0.86      0.52      0.64      5097
         pos       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000

In [54]:
print(confusion_matrix(df['label'], df['comp_score']))

[[2630 2467]
 [ 435 4468]]