What is topic modeling - 
it allows us to efficiently analyzer large volumnes of text by clustering documents into topics. 
    A large amount of text data is unlabeled, meaning we wont be apply to apply our previous supervised learning approaches ,

`m
If we have unlabeled data, then we can attempt to discover labels. 
In that case of text datam this means attemptng to discover the clusters of documents, grouped together by topic

We dont give exact topics - we only cluster them. Topic - we can decide

We will see how Latent Dirichlet Allocation works - LDA

Assumptions - 
Documents with simiklar topics use similar grp of words
Latent topics can then be found by searching for group of words that frequently occur together in documents accorss the corpus

# How LDA works? 
We have a few documents. 
We decide a 'k' - number of topics - we decide it for now. 
Then we go through each document, and randomy assign each word in the document to one of the k topics. 
This gives us word distributions and topic representations. 

Then - we iterate over every word in every document, for each topic t, 
we get 
p(topic t | document d) = proportion of words in document d that are currently assigned to topic t
We get p(word w | topic t) = the proportion of assignments to topic t over all documents that come from this word w 
then we re-assign w - a new topic, where we choose t with probability p(topic t| document d) * p(word w | topic t)

This is probability that topic t generated word w
Then we have each document assigned t a topic. 
Then though it, we can find common words for each topic. "

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("L:\\Workspace\\Resources\\UPDATED_NLP_COURSE\\05-Topic-Modeling\\npr.csv" , sep = "\t")

In [4]:
df.head()

                                             Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [5]:
print(df.iloc[0])

Article    In the Washington of 2016, even when the polic...
Name: 0, dtype: object

In [7]:
# df['Article'][0]

In [8]:
len(df)

11992

In [9]:
df.isnull().sum()

Article    0
dtype: int64

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv = CountVectorizer(max_df=0.9, min_df = 2, stop_words = 'english')
# it will discard words that show up in 90% of documents. That means theya re too common - and are in all the topics. 
#  min_df = word should be in at least this number of or ratio of documents

In [12]:
dtm = cv.fit_transform(df['Article'])

In [13]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3033388 stored elements and shape (11992, 54777)>

In [14]:
from sklearn.decomposition import LatentDirichletAllocation

In [15]:
lda = LatentDirichletAllocation(n_components=7, random_state=42)

In [16]:
 lda.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [18]:
# Grab the vocab of words
len(cv.get_feature_names_out())

#  Grab the topics 


#  Grab the highest probability words per topcs

54777

In [19]:
type(cv.get_feature_names_out())

numpy.ndarray

In [32]:
cv.get_feature_names_out()[41000]

'reproductive'

In [35]:
import random

random_word_id = random.randint(0,54777)
cv.get_feature_names_out()[random_word_id]

'gamesmanship'

In [38]:
len(lda.components_)

7

In [39]:
lda.components_.shape

(7, 54777)

In [40]:
single_topic = lda.components_[0]

In [41]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

What does argssort does???

In [42]:
import numpy as np
arr = np.array([10,200,1])
arr

array([ 10, 200,   1])

In [43]:
arr.argsort()

array([2, 0, 1])

So it sorts and then sends us the original index of the numbers

In [44]:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

for this topic, we got 10 highest probability words

In [52]:
top_ten_words = single_topic.argsort()[-20:]
top_ten_words

array([38079, 46581, 48643, 25406, 50426, 10421, 32089, 54403, 18349,
           1, 33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673,
       42561, 42993])

In [53]:
for index in top_ten_words:
    print(cv.get_feature_names_out()[index])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says

As we can see it is more to do with government -

In [55]:
for index, topic in enumerate(lda.components_):
    print(f"The topc 15 words for topic number {index}")
    print([cv.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
    print("\n\n")

The topc 15 words for topic number 0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']



The topc 15 words for topic number 1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']



The topc 15 words for topic number 2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']



The topc 15 words for topic number 3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']



The topc 15 words for topic number 4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']



The topc 15 words for topic number 5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', 'people', 'just', 'like']



The topc 15 words for topic number 6
['student', 'years', 'data', 'science', 'university', 'people', 'time', 'schools', 'just', 'education', 'new', 'like', 'students', 'school', 'says']

Now we attach this lda with words or documents

In [57]:
df

                                                 Article
0      In the Washington of 2016, even when the polic...
1        Donald Trump has used Twitter  —   his prefe...
2        Donald Trump is unabashedly praising Russian...
3      Updated at 2:50 p. m. ET, Russian President Vl...
4      From photography, illustration and video, to d...
...                                                  ...
11987  The number of law enforcement officers shot an...
11988    Trump is busy these days with victory tours,...
11989  It’s always interesting for the Goats and Soda...
11990  The election of Donald Trump was a surprise to...
11991  Voters in the English city of Sunderland did s...

[11992 rows x 1 columns]

In [58]:
topic_res = lda.transform(dtm)

In [59]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3033388 stored elements and shape (11992, 54777)>

In [61]:
topic_res.shape

(11992, 7)

In [64]:
topic_res[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [65]:
df['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing on CNN, frequent Obama critic Trent Franks,  . called for ”much tougher” actions and said three times that Obama had ”finally found his tongue.” Meanwhile, at    and on Fox News, various spokesmen for   Trump said Obama’s real target was not the Russians at all but the man poised to take over the White House in less than three weeks. They spoke of Obama trying to ”tie Trump’s hands” or ”box him in,” meaning the   would be forced either to keep the sanctions or be at odds with Republicans who want to be tougher still on Moscow. Throughout 2016, Trump has repeatedly called not for sanctions but for closer ties with Russia, including cooperation in the fight against ISIS. Russia has battled ISIS in Syria on behalf of that country’s embattled dictator, Bashar Assad, bombing the besieged   city of Aleppo that fell to Assad’s forces this week. During the campaign, Trump even urged Russia to ”find” missing emails from the private server of his opponent, Hillary Clinton. He has exchanged public encomiums with Russian President Vladimir Putin on several occasions and added his doubts about the current U. S. levels of support for NATO  —   Putin’s longtime nemesis. There have also been suggestions that Trump’s extensive business dealings with various Russians are the reason he refuses to release his tax returns. All those issues have been disquieting to some Republicans for many months. Sens. John McCain,  . and Lindsay Graham,  . C. prominent senior members of the Armed Services Committee, have accepted the assessment of 17 U. S. intelligence agencies regarding the role of Russia in the hacking of various Democratic committees last year. That includes the FBI and CIA consensus that the Russian goal was not just to discredit American democracy but to defeat Clinton and elect Trump. They say the great majority of their Senate colleagues agree with them, and McCain has slated an Armed Services hearing on cyberthreats for Jan. 5. But the politicizing of the Russian actions  —   the idea that they helped Trump win  —   has also made the issue difficult for Republican leaders. It has allowed Trump supporters to push back on the intelligence agencies and say the entire issue is designed to undermine Trump’s legitimacy. Senate Majority Leader Mitch McConnell has so far resisted calls for a select committee to look into the Russian interference in the 2016 campaign. He has said it is enough for Sen. Richard Burr,  . C. to look into it as chairman of the Senate Intelligence Committee. Typically, Republican leaders and spokesmen say there is no evidence that the actual voting or tallying on Nov. 8 was compromised, and that is true. But it is also a red herring, as interference in those functions has not been alleged and is not the focus of the U. S. intelligence agencies’ concern. For his part, Trump has shown little interest in delving into what happened. He has cast doubt on the U. S. intelligence reports to date and suggested ”no one really knows what happened.” He also has suggested that computers make it very difficult to know who is using them. This week, Trump said it was time to ”get on with our lives and do more important things.” However, at week’s end he did agree to have an intelligence briefing on the subject next week. The   has not wanted the daily intelligence briefings available to him in recent weeks, preferring that they be given to the men he has chosen as his vice president (Mike Pence) and national security adviser (Mike Flynn) with Trump taking them only occasionally. The irony of this controversy arising at the eleventh hour of the Obama presidency can scarcely be overstated, and it defines the dilemma facing both the outgoing president and the incoming party in control. Obama appears to have been reluctant to retaliate against the Russian hacking before the election for fear of seeming to interfere with the election himself. The Republicans, meanwhile, have for years called for greater confrontation with the Russians, with Obama usually resisting. Obama did join with NATO in punishing the Russians with economic sanctions over the annexation of Crimea. Those sanctions may have been painful, coming as they did alongside falling prices for oil  —   the commodity that keeps the Russian economy afloat. On other occasions, despite Russian provocations through surrogates in Syria and elsewhere, Obama did not make overt moves to force Russia’s hand. That includes occasions when Russia was believed to be hacking critical computer systems in neighboring Ukraine, Estonia and Poland. But this week, following a chorus of confirmation from the U. S. intelligence community regarding the Russian role in computer hacking in the political campaign, Obama acted. He imposed a set of mostly diplomatic actions such as sanctioning some Russian officials, closing two diplomatic compounds and expelling 35 Russian diplomats. There may have been more damaging measures taken covertly, and some Russophobes in Washington held out hope for that. But the visible portion of the program scarcely amounted to major retribution. And Putin saw fit to diminish the Obama sanctions further by declining to respond. Although his government has steadfastly denied any interference in the U. S. election, Putin rejected his own foreign minister’s recommended package of    responses. (He even sent an invitation for U. S. diplomats to send their children to a holiday party in Moscow.) That allowed Putin to appear for the moment to be ”the bigger man,” even as he spurned Obama and kept up what has looked like a public bromance with Trump, who tweeted: ”Great move on delay (by V. Putin)   I always knew he was very smart!” At the moment it may seem that the overall Russia question amounts to the first crisis facing the Trump presidency. Whether forced by this campaign interference issue or not, Trump must grasp the nettle of a relationship Mitt Romney once called the greatest threat to U. S. security in the world. To be sure, Trump needs to dispel doubts about his ability to stand up to Putin, who has bullied and cajoled his way to center stage in recent world affairs. But Trump also seems determined to turn the page on past U. S. commitments, from free trade philosophy to funding of NATO and the United Nations. And if his Twitter account is any guide, Trump shows little concern about the conundrum others perceive to be facing him. Above all, Trump has shown himself determined to play by his own rules. A year ago, many were confident that would not work for him in the world of presidential politics. We are about to find out whether it works for him in the Oval Office.'

We can see topic index 1 was realted to politics or government - and its true as we can see through the actual article of that number. It is of politics. 

LDA Dont give us topic name - it gives us which article belongs to which number topic - it groups the documents of similar topic - but to name them is our choice